### ISSUE TITLE
nullxlsxonly.js

### ISSUE THREAD

**Issue by codermapuche** [Neovici/nullxlsx#12]
Hello, how can i get nullxlsxonly.js without minified? this project is great and i need modify it for my needs, thanks.

**Comment by jokedst** [comment]
You could just take the files in the src directory and paste together into one big file and name it "nullxlsx.js"

There is no way to create a "nullxlsxonly.js" that is not minified and also does not expose the nullzip parts. It's the minification that "hides" it (or rather, it is allowed to minify the names)
