### ISSUE TITLE
Polyfill TextEncoder for Microsoft IE/Edge

### ISSUE THREAD

**Issue by megheaiulian** [Neovici/nullxlsx#14]
`TextEncoder` is not available on some browsers including Microsoft IE and Edge.
We should maybe include this polyfill https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder#Polyfill or conditionally load it ?

**Comment by nomego** [comment]
Let's not do this and wait with supporting Edge until the Chromium-based one is widely available :)
