### ISSUE TITLE
nullzip compilation problem

### ISSUE THREAD

**Issue by megheaiulian** [Neovici/nullxlsx#9]
For some reason this:
```
 uint16(v) {
    this.dw.setUint16(this.i, v, this.le);
    this.i += 2;
 }
```
gets compiled into that:
```
function y(b, a) {
    b.b.setUint16(b.a, a, !0);
    b.a += 2
}```
Seems closure compiler mixes this with an argument.

**Comment by megheaiulian** [comment]
If you check the code on beta.cosmoz.com you can also see that everything used in this library pollutes global scope. If you check window.a, window.b, .... window.y they are all exported and the 3 files overlap with each other. A closure is needed.

**Comment by megheaiulian** [comment]
@nomego Does this make sense ?

**Comment by nomego** [comment]
Well I'm all for scoping the library to begin with, maybe it will fix the compilation.

**Comment by megheaiulian** [comment]
To improve this and make sure it doesn't happen again we need to:

- [ ] Upgrade closure-compiler version
- [ ] Generate output js files with a wrapper function by using `--output_wrapper` flag
- [ ] Use JSDoc annotation for export instead of the `exports/*.js` files
- [ ] Keep the current tests but add 1-2 tests using the dist version of the libraries
